// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatabaseCRUD.Models
{
    public partial class Owner
    {
        public Owner()
        {
            Dogs = new HashSet<Dog>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }

        public virtual ICollection<Dog> Dogs { get; set; }
    }
}